// Comprehensive categories definition derived from qiira-categories.docx

export interface CategoryDefinition {
    id: string;
    name: string;
    icon: string;
    subcategories: string[];
}

export const BUSINESS_IDENTITY_TYPES: string[] = [
    "Individual Seller",
    "Freelancer",
    "Professional",
    "Artisan",
    "Service Provider",
    "Retailer",
    "Wholesaler",
    "Distributor",
    "Manufacturer",
    "Importer",
    "Exporter",
    "Agency",
    "Company",
    "Organisation",
    "Group / Team",
    "Creator",
    "Public Figure",
    "Artist",
    "Performer",
    "Consultant",
    "NGO / Nonprofit",
    "Community Organisation"
];

export const CATEGORY_DEFINITIONS: CategoryDefinition[] = [
    {
        "id": "media-content-digital-creators",
        "name": "Media, Content & Digital Creators",
        "icon": "videocam-outline",
        "subcategories": [
            "Blogger",
            "Vlogger",
            "Influencer",
            "Content Creator",
            "Social Media Creator",
            "YouTuber",
            "TikTok Creator",
            "Instagram Creator",
            "Facebook Creator",
            "Podcaster",
            "Streamer",
            "Livestreamer",
            "Online Publisher",
            "Online News Platform",
            "Journalist",
            "Photographer",
            "Videographer",
            "Documentary Producer",
            "TV Presenter",
            "Radio Presenter",
            "Broadcaster",
            "Voice-over Artist",
            "Voice Actor",
            "Copywriter",
            "Scriptwriter",
            "Ghostwriter",
            "Author",
            "Editor",
            "Proofreader",
            "Translator",
            "Interpreter",
            "Public Speaker",
            "Motivational Speaker",
            "Media Personality",
            "Brand Ambassador",
            "Celebrity",
            "Digital Creator"
        ]
    },
    {
        "id": "arts-entertainment-performing-arts",
        "name": "Arts, Entertainment & Performing Arts",
        "icon": "musical-notes-outline",
        "subcategories": [
            "Actor",
            "Actress",
            "Film Producer",
            "Film Director",
            "Cinematographer",
            "Screenwriter",
            "Musician",
            "Singer",
            "Rapper",
            "Songwriter",
            "Music Producer",
            "DJ",
            "Band",
            "Orchestra",
            "Choir",
            "Dancer",
            "Dance Group",
            "Choreographer",
            "Comedian",
            "Magician",
            "Theatre Group",
            "Drama Troupe",
            "Performance Artist",
            "Spoken Word Artist",
            "Poet",
            "Painter",
            "Fine Artist",
            "Illustrator",
            "Digital Artist",
            "Sculptor",
            "Cartoonist",
            "Animator",
            "Calligrapher",
            "Tattoo Artist",
            "Caricature Artist"
        ]
    },
    {
        "id": "events-parties-celebrations",
        "name": "Events, Parties & Celebrations",
        "icon": "sparkles-outline",
        "subcategories": [
            "Event Planner",
            "Event Manager",
            "Wedding Planner",
            "Party Planner",
            "Event Decorator",
            "Event Centre",
            "Event Host",
            "MC / Compere",
            "Ushering Agency",
            "Event Usher",
            "Parade Group",
            "Carnival Group",
            "Procession Group",
            "Marching Band",
            "Brass Band",
            "Cultural Group",
            "Cultural Dance Troupe",
            "Traditional Performance Group",
            "Festival Group",
            "Masquerade Group",
            "Drum Group",
            "Entertainment Troupe",
            "Acrobatic Group",
            "Fire Performer",
            "Event Photographer",
            "Event Videographer",
            "Event Livestreaming",
            "Event Equipment Rental",
            "Chair & Table Rental",
            "Canopy / Tent Rental",
            "Stage Rental",
            "Sound System Rental",
            "Lighting Rental",
            "LED Screen Rental",
            "Generator Rental",
            "Event Security",
            "Event Catering",
            "Cake & Dessert Services",
            "Invitation Card Designer",
            "Event Souvenir Seller"
        ]
    },
    {
        "id": "beauty-grooming",
        "name": "Beauty & Grooming",
        "icon": "cut-outline",
        "subcategories": [
            "Hairdresser",
            "Hair Stylist",
            "Barber",
            "Makeup Artist",
            "Henna Artist",
            "Nail Technician",
            "Manicurist",
            "Pedicurist",
            "Eyelash Technician",
            "Brow Artist",
            "Beauty Therapist",
            "Esthetician",
            "Skincare Specialist",
            "Spa",
            "Massage Therapist",
            "Hair Braider",
            "Wig Maker",
            "Wig Seller",
            "Hair Extension Seller",
            "Perfume Seller",
            "Cosmetics Seller",
            "Beauty Product Seller",
            "Skincare Product Seller",
            "Beauty Consultant",
            "Personal Groomer"
        ]
    },
    {
        "id": "fashion-clothing",
        "name": "Fashion & Clothing",
        "icon": "shirt-outline",
        "subcategories": [
            "Fashion Designer",
            "Tailor",
            "Seamstress",
            "Clothing Manufacturer",
            "Boutique",
            "Clothing Store",
            "Online Clothing Seller",
            "Thrift Seller",
            "Vintage Clothing Seller",
            "Fabric Seller",
            "Textile Seller",
            "Traditional Wear Seller",
            "Hijab Seller",
            "Abaya Seller",
            "Kaftan Seller",
            "Suit Seller",
            "Uniform Supplier",
            "Embroidery Service",
            "Clothing Alteration",
            "Shoe Seller",
            "Shoemaker",
            "Sneaker Seller",
            "Sandal Maker",
            "Bag Seller",
            "Bag Maker",
            "Leatherworker",
            "Belt Seller",
            "Jewelry Seller",
            "Bead Maker",
            "Bead Seller",
            "Watch Seller",
            "Sunglasses Seller",
            "Fashion Accessories Seller",
            "Fashion Consultant",
            "Stylist",
            "Personal Shopper"
        ]
    },
    {
        "id": "food-agriculture",
        "name": "Food & Agriculture",
        "icon": "restaurant-outline",
        "subcategories": [
            "Restaurant",
            "Café",
            "Fast Food",
            "Food Vendor",
            "Caterer",
            "Baker",
            "Pastry Seller",
            "Cake Designer",
            "Confectioner",
            "Ice Cream Seller",
            "Juice Seller",
            "Smoothie Seller",
            "Shawarma Seller",
            "Pizza Seller",
            "Grilled Food Vendor",
            "Street Food Vendor",
            "Food Delivery",
            "Grocery Store",
            "Supermarket",
            "Provision Store",
            "Foodstuff Seller",
            "Grain Seller",
            "Rice Seller",
            "Flour Seller",
            "Spice Seller",
            "Vegetable Seller",
            "Fruit Seller",
            "Meat Seller",
            "Butcher",
            "Fish Seller",
            "Frozen Food Seller",
            "Poultry Seller",
            "Egg Seller",
            "Honey Seller",
            "Water Vendor",
            "Farm Produce Seller",
            "Farmer",
            "Poultry Farmer",
            "Fish Farmer",
            "Cattle Farmer",
            "Sheep Farmer",
            "Goat Farmer",
            "Crop Farmer",
            "Livestock Seller",
            "Animal Feed Seller",
            "Seed Seller",
            "Fertilizer Seller",
            "Agrochemical Seller",
            "Agricultural Equipment Seller",
            "Farm Machinery Rental",
            "Agricultural Consultant"
        ]
    },
    {
        "id": "construction-skilled-trades",
        "name": "Construction & Skilled Trades",
        "icon": "hammer-outline",
        "subcategories": [
            "Plumber",
            "Electrician",
            "Carpenter",
            "Mason",
            "Bricklayer",
            "Tiler",
            "Painter",
            "Roofer",
            "Welder",
            "Steel Fabricator",
            "Aluminium Fabricator",
            "Glass Installer",
            "POP Installer",
            "Ceiling Installer",
            "Gypsum Installer",
            "Flooring Installer",
            "Waterproofing Specialist",
            "HVAC Technician",
            "Air Conditioning Technician",
            "Refrigeration Technician",
            "Generator Technician",
            "Solar Installer",
            "Solar Technician",
            "Borehole Installer",
            "Water Treatment Specialist",
            "Building Contractor",
            "Civil Engineer",
            "Architect",
            "Quantity Surveyor",
            "Town Planner",
            "Surveyor",
            "Geologist",
            "Interior Designer",
            "Landscape Designer",
            "Property Maintenance",
            "Construction Company"
        ]
    },
    {
        "id": "home-domestic-services",
        "name": "Home & Domestic Services",
        "icon": "home-outline",
        "subcategories": [
            "House Cleaner",
            "Commercial Cleaner",
            "Laundry",
            "Dry Cleaner",
            "Carpet Cleaner",
            "Upholstery Cleaner",
            "Window Cleaner",
            "Pest Control",
            "Fumigation",
            "Gardener",
            "Landscaper",
            "Domestic Worker",
            "Housekeeper",
            "Nanny",
            "Babysitter",
            "Caregiver",
            "Personal Assistant",
            "Cook / Private Chef",
            "Handyman",
            "Locksmith",
            "Home Maintenance",
            "Furniture Repair",
            "Appliance Repair",
            "Home Organisation Service"
        ]
    },
    {
        "id": "real-estate-property",
        "name": "Real Estate & Property",
        "icon": "business-outline",
        "subcategories": [
            "Real Estate Agent",
            "Realtor",
            "Property Developer",
            "Property Manager",
            "Estate Management Company",
            "Facility Manager",
            "Land Agent",
            "Land Seller",
            "Property Seller",
            "House Seller",
            "House Rental",
            "Apartment Rental",
            "Short-Let",
            "Serviced Apartment",
            "Student Accommodation",
            "Commercial Property",
            "Property Valuer",
            "Estate Consultant",
            "Real Estate Photographer",
            "Property Marketing",
            "Property Documentation Services"
        ]
    },
    {
        "id": "automotive-transportation",
        "name": "Automotive & Transportation",
        "icon": "car-outline",
        "subcategories": [
            "Car Dealer",
            "Used Car Dealer",
            "Motorcycle Dealer",
            "Tricycle Dealer",
            "Vehicle Importer",
            "Auto Parts Seller",
            "Motorcycle Parts Seller",
            "Mechanic",
            "Auto Electrician",
            "Auto Diagnostic Technician",
            "Tyre Seller",
            "Vulcanizer",
            "Battery Seller",
            "Car Wash",
            "Car Detailing",
            "Auto Body Repair",
            "Panel Beater",
            "Spray Painter",
            "Vehicle Towing",
            "Vehicle Recovery",
            "Driving School",
            "Driver",
            "Chauffeur",
            "Taxi",
            "Ride-Hailing Driver",
            "Car Rental",
            "Bus Rental",
            "Truck Rental",
            "Logistics Company",
            "Transport Company",
            "Moving Company"
        ]
    },
    {
        "id": "technology-it",
        "name": "Technology & IT",
        "icon": "laptop-outline",
        "subcategories": [
            "Software Developer",
            "Web Developer",
            "Mobile App Developer",
            "UI/UX Designer",
            "Graphic Designer",
            "IT Consultant",
            "IT Support",
            "Computer Technician",
            "Phone Repairer",
            "Electronics Repairer",
            "Cybersecurity Specialist",
            "Network Engineer",
            "Systems Administrator",
            "Database Administrator",
            "Cloud Specialist",
            "Data Analyst",
            "AI Specialist",
            "AI Consultant",
            "Machine Learning Developer",
            "Robotics Specialist",
            "Blockchain Developer",
            "Game Developer",
            "Game Designer",
            "Computer Trainer",
            "Coding Instructor",
            "Website Designer",
            "Domain / Hosting Provider",
            "Digital Solutions Company",
            "SaaS Company",
            "POS Services",
            "CCTV Installer",
            "Access Control Installer",
            "Biometric Systems",
            "Networking Services",
            "Printer Repair",
            "Photocopier Services",
            "Data Recovery",
            "Cyber Café"
        ]
    },
    {
        "id": "electronics-retail",
        "name": "Electronics & Retail",
        "icon": "hardware-chip-outline",
        "subcategories": [
            "Phone Seller",
            "Smartphone Seller",
            "Laptop Seller",
            "Computer Seller",
            "Tablet Seller",
            "Television Seller",
            "Camera Seller",
            "Gaming Console Seller",
            "Home Appliance Seller",
            "Refrigerator Seller",
            "Air Conditioner Seller",
            "Generator Seller",
            "Solar Equipment Seller",
            "Inverter Seller",
            "Electronics Store",
            "Phone Accessories Seller",
            "Computer Accessories Seller",
            "Gaming Accessories Seller",
            "Electrical Materials Seller",
            "Battery Seller"
        ]
    },
    {
        "id": "professional-services",
        "name": "Professional Services",
        "icon": "briefcase-outline",
        "subcategories": [
            "Lawyer",
            "Legal Consultant",
            "Accountant",
            "Auditor",
            "Tax Consultant",
            "Financial Consultant",
            "Business Consultant",
            "Management Consultant",
            "HR Consultant",
            "Recruitment Agency",
            "Marketing Consultant",
            "PR Consultant",
            "Communications Consultant",
            "Branding Consultant",
            "Political Consultant",
            "Public Affairs Consultant",
            "Research Consultant",
            "Project Manager",
            "Procurement Consultant",
            "Management Agency",
            "Secretarial Services",
            "Virtual Assistant",
            "Freelancer",
            "Business Coach",
            "Career Coach",
            "Life Coach",
            "Executive Coach"
        ]
    },
    {
        "id": "finance-payments",
        "name": "Finance & Payments",
        "icon": "cash-outline",
        "subcategories": [
            "Bank Agent",
            "POS Agent",
            "Money Transfer Agent",
            "Payment Agent",
            "Bureau de Change",
            "Microfinance",
            "Cooperative",
            "Savings Group",
            "Loan Service",
            "Insurance Agent",
            "Insurance Broker",
            "Investment Consultant",
            "Financial Planner",
            "Accounting Service",
            "Bookkeeping Service",
            "Tax Filing Service"
        ]
    },
    {
        "id": "education-training",
        "name": "Education & Training",
        "icon": "school-outline",
        "subcategories": [
            "School",
            "Nursery School",
            "Primary School",
            "Secondary School",
            "University Lecturer",
            "Polytechnic Lecturer",
            "Professor",
            "Vocational School",
            "Tutorial Centre",
            "Private Tutor",
            "Online Tutor",
            "Language Teacher",
            "Quran Teacher",
            "Islamic Studies Teacher",
            "Computer Trainer",
            "Coding Instructor",
            "Driving Instructor",
            "Music Teacher",
            "Dance Instructor",
            "Art Teacher",
            "Skills Trainer",
            "Corporate Trainer",
            "Professional Certification Trainer",
            "Educational Consultant",
            "Study Abroad Consultant",
            "Examination Preparation Centre"
        ]
    },
    {
        "id": "health-medical-wellness",
        "name": "Health, Medical & Wellness",
        "icon": "medkit-outline",
        "subcategories": [
            "Hospital",
            "Clinic",
            "Pharmacy",
            "Medical Laboratory",
            "Diagnostic Centre",
            "Dental Clinic",
            "Optician",
            "Optical Centre",
            "Physiotherapist",
            "Fitness Centre",
            "Gym",
            "Personal Trainer",
            "Yoga Instructor",
            "Wellness Centre",
            "Nutritionist",
            "Dietitian",
            "Medical Equipment Seller",
            "Medical Supplies Seller",
            "Health Product Seller",
            "Elderly Care",
            "Home Healthcare",
            "Medical Doctor",
            "Nurse",
            "Pharmacist",
            "Medical Laboratory Scientist",
            "Community Health Worker"
        ]
    },
    {
        "id": "travel-hospitality",
        "name": "Travel & Hospitality",
        "icon": "airplane-outline",
        "subcategories": [
            "Hotel",
            "Guest House",
            "Resort",
            "Lodge",
            "Hostel",
            "Short-Let",
            "Travel Agency",
            "Tour Operator",
            "Tour Guide",
            "Tourist Attraction",
            "Ticketing Agent",
            "Flight Booking",
            "Hotel Booking",
            "Visa Assistance",
            "Travel Consultant",
            "Car Rental",
            "Airport Transfer",
            "Tourism Photographer"
        ]
    },
    {
        "id": "logistics-delivery",
        "name": "Logistics & Delivery",
        "icon": "cube-outline",
        "subcategories": [
            "Courier",
            "Dispatch Rider",
            "Delivery Service",
            "Food Delivery",
            "Parcel Delivery",
            "Freight Forwarder",
            "Haulage",
            "Trucking",
            "Warehousing",
            "Storage",
            "Moving Company",
            "Import / Export Logistics",
            "Shipping Agent",
            "Clearing & Forwarding Agent"
        ]
    },
    {
        "id": "politics-civic-public-affairs",
        "name": "Politics, Civic & Public Affairs",
        "icon": "flag-outline",
        "subcategories": [
            "Politician",
            "Political Party",
            "Political Office",
            "Political Consultant",
            "Campaign Consultant",
            "Campaign Organisation",
            "Political Strategist",
            "Political Communications",
            "Public Affairs Consultant",
            "Government Relations",
            "Advocacy Organisation",
            "NGO",
            "Nonprofit Organisation",
            "Civil Society Organisation",
            "Community Organisation",
            "Youth Organisation",
            "Women’s Organisation",
            "Professional Association",
            "Trade Association",
            "Community Leader",
            "Traditional Institution",
            "Religious Organisation"
        ]
    },
    {
        "id": "agriculture-animals-pets",
        "name": "Agriculture, Animals & Pets",
        "icon": "leaf-outline",
        "subcategories": [
            "Veterinary Clinic",
            "Veterinarian",
            "Pet Shop",
            "Pet Groomer",
            "Pet Trainer",
            "Pet Sitter",
            "Dog Breeder",
            "Animal Breeder",
            "Poultry Farm",
            "Fish Farm",
            "Cattle Farm",
            "Livestock Farm",
            "Animal Feed Seller",
            "Farm Equipment Seller",
            "Farm Labour Services"
        ]
    },
    {
        "id": "security-safety",
        "name": "Security & Safety",
        "icon": "shield-checkmark-outline",
        "subcategories": [
            "Security Company",
            "Private Security",
            "Security Guard",
            "Bodyguard",
            "Event Security",
            "CCTV Services",
            "Alarm Systems",
            "Access Control",
            "Security Equipment Seller",
            "Fire Safety Services",
            "Fire Extinguisher Seller",
            "Safety Equipment Seller",
            "Safety Consultant"
        ]
    },
    {
        "id": "printing-advertising-branding",
        "name": "Printing, Advertising & Branding",
        "icon": "print-outline",
        "subcategories": [
            "Printing Press",
            "Digital Printer",
            "Graphic Designer",
            "Sign Maker",
            "Signage Company",
            "Billboard Company",
            "Advertising Agency",
            "Branding Agency",
            "Digital Marketing Agency",
            "Social Media Agency",
            "PR Agency",
            "Promotional Products Seller",
            "T-Shirt Printer",
            "Embroidery Service",
            "Packaging Company",
            "Publishing Company",
            "Magazine",
            "Newspaper",
            "Media House"
        ]
    },
    {
        "id": "crafts-handmade-products",
        "name": "Crafts & Handmade Products",
        "icon": "color-palette-outline",
        "subcategories": [
            "Potter",
            "Ceramic Artist",
            "Basket Maker",
            "Mat Maker",
            "Weaver",
            "Leather Artisan",
            "Wood Carver",
            "Sculptor",
            "Bead Maker",
            "Jewellery Maker",
            "Traditional Craftsman",
            "Handmade Gift Maker",
            "Candle Maker",
            "Soap Maker",
            "Perfume Maker",
            "Artisan",
            "Craft Store"
        ]
    },
    {
        "id": "religious-cultural-services",
        "name": "Religious & Cultural Services",
        "icon": "book-outline",
        "subcategories": [
            "Religious Teacher",
            "Quran Teacher",
            "Islamic Scholar",
            "Religious Book Seller",
            "Religious Clothing Seller",
            "Religious Items Seller",
            "Nikah Services",
            "Religious Event Services",
            "Cultural Group",
            "Traditional Performer",
            "Traditional Craftsman",
            "Cultural Festival Organiser"
        ]
    },
    {
        "id": "personal-services",
        "name": "Personal Services",
        "icon": "person-outline",
        "subcategories": [
            "Personal Shopper",
            "Errand Service",
            "Personal Assistant",
            "Concierge",
            "Matchmaking Service",
            "Life Coach",
            "Personal Trainer",
            "Fitness Coach",
            "Tutor",
            "Caregiver",
            "Nanny",
            "Babysitter",
            "Driver",
            "Domestic Worker",
            "Housekeeper"
        ]
    },
    {
        "id": "funeral-services",
        "name": "Funeral Services",
        "icon": "heart-outline",
        "subcategories": [
            "Funeral Home",
            "Mortuary Services",
            "Funeral Planner",
            "Coffin / Casket Seller",
            "Funeral Transport",
            "Grave / Cemetery Services",
            "Funeral Decoration",
            "Funeral Catering",
            "Funeral Photography",
            "Funeral Videography"
        ]
    },
    {
        "id": "waste-environmental-services",
        "name": "Waste & Environmental Services",
        "icon": "trash-outline",
        "subcategories": [
            "Waste Collection",
            "Recycling",
            "Scrap Dealer",
            "Environmental Consultant",
            "Sanitation Services",
            "Waste Disposal",
            "Sewage Services",
            "Drainage Services",
            "Environmental Cleaning"
        ]
    },
    {
        "id": "industrial-services",
        "name": "Industrial Services",
        "icon": "cog-outline",
        "subcategories": [
            "Industrial Equipment Seller",
            "Machinery Seller",
            "Equipment Rental",
            "Generator Services",
            "Welding & Fabrication",
            "Factory",
            "Manufacturing",
            "Industrial Maintenance",
            "Industrial Cleaning",
            "Packaging",
            "Raw Materials Supplier"
        ]
    },
    {
        "id": "private-investigation-risk-services",
        "name": "Private Investigation & Risk Services",
        "icon": "search-outline",
        "subcategories": [
            "Private Investigator",
            "Background Check Service",
            "Security Consultant",
            "Risk Management",
            "Security Training",
            "Fraud Investigation",
            "Due Diligence Services"
        ]
    },
    {
        "id": "sports",
        "name": "Sports",
        "icon": "football-outline",
        "subcategories": [
            "Football Academy",
            "Football Club",
            "Sports Club",
            "Sports Coach",
            "Personal Trainer",
            "Sports Photographer",
            "Sports Equipment Seller",
            "Fitness Centre",
            "Martial Arts Instructor",
            "Boxing Gym",
            "Swimming Instructor",
            "Sports Event Organiser",
            "Sports Facility",
            "Sports Agent"
        ]
    },
    {
        "id": "children-family",
        "name": "Children & Family",
        "icon": "happy-outline",
        "subcategories": [
            "Daycare",
            "Nursery",
            "Babysitter",
            "Children’s Party Planner",
            "Children’s Entertainment",
            "Toy Seller",
            "Baby Products Seller",
            "Maternity Products Seller",
            "Parenting Consultant",
            "Children’s Clothing Seller",
            "Children’s Shoe Seller"
        ]
    },
    {
        "id": "models-fashion-creators",
        "name": "Models & Fashion Creators",
        "icon": "camera-outline",
        "subcategories": [
            "Model",
            "Fashion Model",
            "Commercial Model",
            "Brand Ambassador",
            "Influencer",
            "Stylist",
            "Fashion Blogger",
            "Fashion Photographer",
            "Fashion Content Creator"
        ]
    },
    {
        "id": "clubs-groups-communities",
        "name": "Clubs, Groups & Communities",
        "icon": "people-outline",
        "subcategories": [
            "Reading Club",
            "Book Club",
            "Writing Club",
            "Writers’ Group",
            "Poetry Club",
            "Debate Club",
            "Public Speaking Club",
            "Literature Club",
            "Arts & Crafts Club",
            "Photography Club",
            "Film Club",
            "Music Club",
            "Drama Club",
            "Theatre Group",
            "Dance Group",
            "Cultural Group",
            "Heritage Group",
            "History Club",
            "Science Club",
            "Technology Club",
            "Coding Club",
            "Robotics Club",
            "Innovation Club",
            "Entrepreneurship Club",
            "Business Club",
            "Investment Club",
            "Finance Club",
            "Career Club",
            "Professional Network",
            "Networking Group",
            "Alumni Association",
            "Students’ Association",
            "Youth Group",
            "Women’s Group",
            "Men’s Group",
            "Community Group",
            "Neighbourhood Association",
            "Residents’ Association",
            "Social Club",
            "Friendship Club",
            "Hobby Club",
            "Interest Group",
            "Fan Club",
            "Support Group",
            "Volunteer Group",
            "Charity Group",
            "Community Service Group",
            "Advocacy Group",
            "Humanitarian Group"
        ]
    },
    {
        "id": "sports-clubs-teams",
        "name": "Sports Clubs & Teams",
        "icon": "trophy-outline",
        "subcategories": [
            "Football Club",
            "Football Academy",
            "Basketball Club",
            "Volleyball Club",
            "Handball Club",
            "Tennis Club",
            "Table Tennis Club",
            "Athletics Club",
            "Cycling Club",
            "Swimming Club",
            "Boxing Club",
            "Wrestling Club",
            "Martial Arts Club",
            "Karate Club",
            "Taekwondo Club",
            "Fitness Club",
            "Running Club",
            "Hiking Club",
            "Gymnastics Club",
            "Sports Academy",
            "Sports Team",
            "Supporters Club",
            "Sports Association",
            "E-Sports Team",
            "Gaming Club"
        ]
    },
    {
        "id": "religious-groups-organisations",
        "name": "Religious Groups & Organisations",
        "icon": "flame-outline",
        "subcategories": [
            "Religious Organisation",
            "Mosque Organisation",
            "Church Organisation",
            "Islamic Society",
            "Muslim Youth Group",
            "Christian Youth Group",
            "Quran Study Group",
            "Bible Study Group",
            "Islamic Study Circle",
            "Religious Study Group",
            "Da’wah Organisation",
            "Missionary Organisation",
            "Religious Charity",
            "Religious School",
            "Religious Community",
            "Faith-Based Organisation"
        ]
    },
    {
        "id": "professional-business-groups",
        "name": "Professional & Business Groups",
        "icon": "podium-outline",
        "subcategories": [
            "Business Association",
            "Traders Association",
            "Market Association",
            "Professional Association",
            "Industry Association",
            "Entrepreneurs Network",
            "Startup Community",
            "Business Network",
            "Chamber of Commerce",
            "Cooperative Society",
            "Trade Union",
            "Workers’ Association",
            "Employers’ Association",
            "Artisans Association",
            "Farmers Association",
            "Transport Workers Association",
            "Landlords Association",
            "Tenants Association",
            "Professional Network",
            "Business Referral Group"
        ]
    },
    {
        "id": "creative-entertainment-groups",
        "name": "Creative & Entertainment Groups",
        "icon": "film-outline",
        "subcategories": [
            "Music Group",
            "Band",
            "Choir",
            "Orchestra",
            "Dance Troupe",
            "Drama Troupe",
            "Theatre Company",
            "Comedy Group",
            "Film Club",
            "Film Production Team",
            "Creative Collective",
            "Artists’ Collective",
            "Writers’ Collective",
            "Photographers’ Group",
            "Content Creators’ Group",
            "Influencers’ Network",
            "DJs Association",
            "MCs Association",
            "Actors’ Association",
            "Musicians’ Association",
            "Artists’ Association",
            "Performers’ Association"
        ]
    },
    {
        "id": "cultural-traditional-groups",
        "name": "Cultural & Traditional Groups",
        "icon": "globe-outline",
        "subcategories": [
            "Cultural Association",
            "Cultural Group",
            "Traditional Dance Group",
            "Traditional Music Group",
            "Heritage Society",
            "Cultural Society",
            "Festival Committee",
            "Carnival Group",
            "Parade Group",
            "Masquerade Group",
            "Traditional Rulers’ Organisation",
            "Community Development Association",
            "Indigenous Community Association",
            "Ethnic Cultural Organisation",
            "Language Preservation Group",
            "Historical Society",
            "Heritage Preservation Group"
        ]
    },
    {
        "id": "educational-academic-groups",
        "name": "Educational & Academic Groups",
        "icon": "library-outline",
        "subcategories": [
            "Reading Club",
            "Book Club",
            "Study Group",
            "Research Group",
            "Academic Society",
            "Students’ Club",
            "Students’ Association",
            "Debate Society",
            "Literary Society",
            "Science Club",
            "Mathematics Club",
            "Computer Club",
            "Coding Club",
            "Robotics Club",
            "Engineering Society",
            "Medical Students’ Group",
            "Law Students’ Group",
            "Alumni Association",
            "Teachers’ Association",
            "Academic Network",
            "Research Society",
            "Learning Community",
            "Study Circle",
            "Tutorial Group"
        ]
    },
    {
        "id": "charity-ngo-social-impact-groups",
        "name": "Charity, NGO & Social Impact Groups",
        "icon": "hand-left-outline",
        "subcategories": [
            "NGO",
            "Nonprofit Organisation",
            "Charity",
            "Foundation",
            "Humanitarian Organisation",
            "Community Development Organisation",
            "Volunteer Organisation",
            "Youth Development Organisation",
            "Women Empowerment Organisation",
            "Child Welfare Organisation",
            "Disability Support Organisation",
            "Environmental Organisation",
            "Poverty Alleviation Organisation",
            "Education Charity",
            "Health Charity",
            "Orphan Support Organisation",
            "Elderly Support Organisation",
            "Disaster Relief Organisation",
            "Refugee / IDP Support Organisation",
            "Community Service Group"
        ]
    },
    {
        "id": "social-lifestyle-groups",
        "name": "Social & Lifestyle Groups",
        "icon": "wine-outline",
        "subcategories": [
            "Social Club",
            "Friends’ Group",
            "Singles Club",
            "Couples’ Club",
            "Parenting Group",
            "Mothers’ Group",
            "Fathers’ Group",
            "Hobby Club",
            "Travel Club",
            "Adventure Club",
            "Food Club",
            "Cooking Club",
            "Gardening Club",
            "Car Club",
            "Motorcycle Club",
            "Fashion Club",
            "Beauty Community",
            "Lifestyle Community",
            "Wellness Community",
            "Fitness Community",
            "Pet Owners’ Group",
            "Gaming Community",
            "Collectors’ Club"
        ]
    },
    {
        "id": "technology-digital-communities",
        "name": "Technology & Digital Communities",
        "icon": "code-slash-outline",
        "subcategories": [
            "Tech Community",
            "Developers’ Community",
            "Programmers’ Group",
            "Coding Club",
            "AI Community",
            "Data Science Community",
            "Cybersecurity Community",
            "Blockchain Community",
            "Startup Community",
            "Digital Creators’ Community",
            "UX/UI Community",
            "Open Source Community",
            "Gaming Community",
            "E-Sports Community",
            "Tech Users’ Group",
            "Innovation Hub",
            "Makerspace Community"
        ]
    },
    {
        "id": "political-civic-groups",
        "name": "Political & Civic Groups",
        "icon": "ribbon-outline",
        "subcategories": [
            "Political Party",
            "Political Movement",
            "Campaign Group",
            "Political Support Group",
            "Youth Political Group",
            "Women’s Political Group",
            "Constituency Group",
            "Ward Organisation",
            "Community Political Group",
            "Civic Organisation",
            "Civic Engagement Group",
            "Voters’ Education Group",
            "Advocacy Group",
            "Policy Discussion Group",
            "Public Affairs Organisation",
            "Think Tank",
            "Governance Forum"
        ]
    },
    {
        "id": "associations-membership-organisations",
        "name": "Associations & Membership Organisations",
        "icon": "id-card-outline",
        "subcategories": [
            "Association",
            "Society",
            "Club",
            "Union",
            "Cooperative",
            "Federation",
            "Council",
            "Network",
            "Foundation",
            "Institute",
            "Forum",
            "Community",
            "Collective",
            "Coalition",
            "Movement",
            "Chapter",
            "Alumni Group",
            "Residents’ Association",
            "Professional Body",
            "Trade Body",
            "Student Organisation"
        ]
    },
    {
        "id": "event-based-groups",
        "name": "Event-Based Groups",
        "icon": "calendar-outline",
        "subcategories": [
            "Wedding Group",
            "Bridal Team",
            "Groomsmen Group",
            "Birthday Planning Group",
            "Festival Committee",
            "Event Committee",
            "Parade Group",
            "Carnival Group",
            "Concert Team",
            "Production Crew",
            "Event Staff",
            "Ushering Team",
            "Security Team",
            "Media Team",
            "Volunteer Team",
            "Protocol Team",
            "Hospitality Team"
        ]
    }
];

export const BUSINESS_CATEGORIES: string[] = CATEGORY_DEFINITIONS.map(c => c.name);

// Top popular categories for quick filtering and horizontal chips
export const POPULAR_CATEGORIES: string[] = [
    "All",
    "Food & Agriculture",
    "Fashion & Clothing",
    "Beauty & Grooming",
    "Technology & IT",
    "Electronics & Retail",
    "Automotive & Transportation",
    "Real Estate & Property",
    "Health, Medical & Wellness",
    "Events, Parties & Celebrations",
    "Media, Content & Digital Creators",
    "Arts, Entertainment & Performing Arts",
    "Professional Services",
    "Home & Domestic Services",
    "Education & Training"
];

export function searchCategoriesAndSubcategories(query: string): { category: string; matchedSubcategories: string[] }[] {
    const clean = query.trim().toLowerCase();
    if (!clean) return CATEGORY_DEFINITIONS.map(c => ({ category: c.name, matchedSubcategories: c.subcategories }));
    const results: { category: string; matchedSubcategories: string[] }[] = [];
    for (const cat of CATEGORY_DEFINITIONS) {
        const catMatches = cat.name.toLowerCase().includes(clean);
        const subMatches = cat.subcategories.filter(s => s.toLowerCase().includes(clean));
        if (catMatches || subMatches.length > 0) {
            results.push({
                category: cat.name,
                matchedSubcategories: catMatches ? cat.subcategories : subMatches
            });
        }
    }
    return results;
}
